In [2]:
import pandas as pd, numpy as np

## `in` with Series

In [9]:
s = pd.Series(range(10,20)); s

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [14]:
11 in s, 11 in list(s)

(False, True)

## df equality

In [15]:
import pandas as pd 
import numpy as np

In [16]:
def make_dfs(*args):
    np.random.seed(0)
    df1 = pd.DataFrame(np.random.rand(*args))
    np.random.seed(0)
    df2 = pd.DataFrame(np.random.rand(*args))
    return df1, df2 
df1, df2 = make_dfs(10,1)

In [17]:
df1.head()

          0
0  0.548814
1  0.715189
2  0.602763
3  0.544883
4  0.423655

In [18]:
df2.head()

          0
0  0.548814
1  0.715189
2  0.602763
3  0.544883
4  0.423655

In [20]:
df1==df2

      0
0  True
1  True
2  True
3  True
4  True
5  True
6  True
7  True
8  True
9  True

In [21]:
(df1 == df2).all()

0    True
dtype: bool

In [22]:
(df1 == df2).all().all()

True

# identical columns

In [7]:
df=pd.DataFrame(np.random.rand(3,2), columns=['yes','yes']); df

        yes       yes
0  0.697827  0.756066
1  0.483060  0.834582
2  0.611664  0.001328

In [8]:
df['yes']

        yes       yes
0  0.697827  0.756066
1  0.483060  0.834582
2  0.611664  0.001328

In [17]:
df.loc[:,['yes']]

        yes       yes
0  0.697827  0.756066
1  0.483060  0.834582
2  0.611664  0.001328

# quartile binning

In [18]:
s = pd.Series(np.random.rand(100)); s

0     0.108511
1     0.221347
2     0.239827
3     0.633540
4     0.648709
        ...
95    0.593336
96    0.849349
97    0.407497
98    0.225728
99    0.707092
Length: 100, dtype: float64

In [22]:
df = pd.DataFrame([s, pd.qcut(s, [0,0.25,0.5,0.75,1.])]).T
df

           0                 1
0   0.108511  (0.00893, 0.321]
1   0.221347  (0.00893, 0.321]
2   0.239827  (0.00893, 0.321]
3    0.63354    (0.535, 0.779]
4   0.648709    (0.535, 0.779]
..       ...               ...
95  0.593336    (0.535, 0.779]
96  0.849349    (0.779, 0.988]
97  0.407497    (0.321, 0.535]
98  0.225728  (0.00893, 0.321]
99  0.707092    (0.535, 0.779]

[100 rows x 2 columns]

In [19]:
pd.qcut(s, [0,0.25,0.5,0.75,1.]).value_counts()

(0.00893, 0.321]    25
(0.321, 0.535]      25
(0.535, 0.779]      25
(0.779, 0.988]      25
Name: count, dtype: int64