In [1]:
import pandas as pd

## `in` with Series

In [9]:
s = pd.Series(range(10,20)); s

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [14]:
11 in s, 11 in list(s)

(False, True)

## df equality

In [15]:
import pandas as pd 
import numpy as np

In [16]:
def make_dfs(*args):
    np.random.seed(0)
    df1 = pd.DataFrame(np.random.rand(*args))
    np.random.seed(0)
    df2 = pd.DataFrame(np.random.rand(*args))
    return df1, df2 
df1, df2 = make_dfs(10,1)

In [17]:
df1.head()

          0
0  0.548814
1  0.715189
2  0.602763
3  0.544883
4  0.423655

In [18]:
df2.head()

          0
0  0.548814
1  0.715189
2  0.602763
3  0.544883
4  0.423655

In [20]:
df1==df2

      0
0  True
1  True
2  True
3  True
4  True
5  True
6  True
7  True
8  True
9  True

In [21]:
(df1 == df2).all()

0    True
dtype: bool

In [22]:
(df1 == df2).all().all()

True